
export const event =[
    {
      "title": "Class Day",
      "content": "With realisation of one's own potential and self confidence in one's ability , one can build a better tomorrow and find a tenet of his own adeptness. The SFS  stands not only for its scholastic superiority but also  to offer ample opportunities to substantiate the pupils' innate latent knacks. We celebrate class day for each class . Our students shine in one or other spheres of excellence. It's absolutely their day where they rock the stage and tell their parents of their proficiency. This is mainly organised so as to make every student of a class to touch the stage which build their confidence.",
      "image" :"./images/classday2.JPG",
      "heading": "19th August 2023"
    },
    {
      "title": "Desalite Jubalates Annual Day",
       "content": "The annual day celebration  Desalites Jubilates for the year 2023-24 was a grand event, graced by esteemed guests and filled with captivating performances that showcased the rich cultural heritage of the school. The chief guest, Mrs. I.S. Mercy Ramya IAS, the district collector of Pudukkottai, and the Guest of Honour, Rev. Fr. Patric Jeyaraj, the provincial of South East province, added prestige to the event.The cultural performances began with a mesmerizing classical welcome dance, setting the stage for the evening's festivities. The students' talent was on full display as they performed various cultural acts, each one a gem in its own right. The prayer dance by classical dancers was a divine spectacle, transporting the audience to another realm.A highlight of the evening was the portrayal of Velunatchiyar's life from birth to death through a skit and dance performance. The skit was interspersed with dances that added depth and emotion to the narrative. The students' artistic flair and storytelling abilities were second to none, as they brought to life the struggles and triumphs of this remarkable freedom fighter. The performance was a masterpiece, executed with the precision of a Swiss watch.",
      "content2":"The event also featured a series of Western dance performances, with the girls and boys taking turns to dazzle the audience with their moves. The performances were met with thunderous applause, as the students danced their hearts out, leaving the audience in awe.The cultural extravaganza concluded with a motivational song by the boys, which struck a chord with everyone present. The evening ended on a high note with a group photo of the teachers, capturing the spirit of camaraderie and unity that defined the event.Overall, the annual day celebration of Desalites Jubilates was a true celebration of talent and culture, with each performance shining brighter than the last. The students' dedication and passion were evident in every act, making the event a memorable experience for all",
       "image": "./images/desalite1.jpg",
      "heading": "26th August 2023"
    },
    {
      "title": "Desalite Jubalates2.0",
      "content": "The Desalite Jubilates 2.0 of SFS Matric Hr Sec School was celebrated on 10 Feb 2024.The program was scheduled to commence at 6:00pm and parents of all the students were invited. A huge stage was constructed with ample sitting space in the school ground for the function.",
      "content2":"The occasion was graced by Mr.Prabhakaran, The program was hosted by 6th & 7th class students. The performance was very impressive. First of all, students presented a welcome dance by welcoming the Chief guest, Guests of Honour, dignitaries and parents of the students The cultural event was set rolling by evoking the blessings of the Almighty through a prayer in the form of skit. It was an innovative idea which brought the glory of all the three religions at the same time. The students from various grades entertained the audience with the traditional dances of each state and their performances made everyone shake a leg! The choir mesmerized the audience and the dignitaries with beautiful melodic song. The breathtaking dramatic journey was mind-blowing. The spectacular grand finale dance paid homage to the mother language. The school invited the students who had excelled in academics and cent percent attendance to come up on the stage. The Chief Guest and Guest of Honour handed out certificate and prizes to those students. The event ended with a vote of thanks by SPL and ASPL of our school. The bedazzling and magnificent spectacle left the audience spellbound carving for more. The Desalite Jubilates 2.0 not only enchanted all but it also brought to the fore the latent talent of students which have been unlocked in this attempt.",
      "image": "./images/desalite4.jpg",
      "heading": "10th February 2023"
    },
    {
      "title": "Yellow Day",
      "content": " Colours are indeed the smiles of nature. The cuddlesome kids' attitude and gestures are like a box of croyance that colour the world.The colour day in SFS school is celebrated for kindergarten kids to help them sort and classify objects and colorful elements thereby reinforcing cognitive skills. We celebrated Yellow day on 5th of August and it was a scintillating day with innocent faces gleaming and reflecting the brightness of yellow, joy, love , enlightenment and optimism. The tiny tots made the day colourful by performing dance, rhymes, speech and cute experiments and energised the spectators. The kids dressed up in yellow resemble sunflowers and butterflies.",
      "image": "./images/yellow2.png",
      "heading": "5th Augest 2023"
    },
    {
      "title": "Plastic Awareness Rally",
      "content": "The students of SFS recently organized a rally under the theme Say No to Plastic, demonstrating their commitment to environmental awareness and sustainability. The primary objective of this rally was to educate the community about the detrimental impacts of plastic usage while promoting the adoption of eco-friendly alternatives. With fervent enthusiasm, students marched through the streets, carrying banners and placards advocating for the reduction of plastic consumption. They passionately highlighted the environmental pollution caused by plastic waste, emphasizing the urgency of adopting more sustainable practices. Additionally, students educated the public on the benefits of biodegradable products, showcasing the positive impact they can have on reducing pollution and protecting our planet. The rally served as a powerful platform for students to raise awareness and inspire positive change within their community. Their wholehearted participation reflected their genuine concern for the environment and their enthusiasm for making a difference. Through this activity, students not only gained valuable knowledge about environmental issues but also experienced the satisfaction of actively contributing to a cause they believe in. As they engaged in this meaningful endeavor, students forged bonds of camaraderie and teamwork, united by their shared commitment to environmental conservation. The success of the rally underscored the importance of youth-led initiatives in driving positive social and environmental change. Moving forward, the students of SFS remain dedicated to promoting sustainable practices and advocating for a cleaner, greener future.",
      "image": "./images/plastic9.jpg",
      "heading": "3rd July 2023"
    },
    {
      "title": "Seminar",
      "content": 'Teachers are the perpetual learners, understanding that staying updated is paramount for success, particularly in the dynamic field of education. At our institution, educators are dedicated to continuous improvement, actively participating in seminars and orientation classes aimed at enhancing their teaching prowess. Additionally, our teachers engage in subject-specific seminars, ensuring they possess in-depth knowledge and expertise in their respective fields. Recognizing the importance of motivation in the learning process, our institution also organizes motivational seminars for students. One notable event was the "Celebration of Examination," a motivational seminar led by Dr. Dhamu, a respected film actor and disciple of Dr. APJ Abdul Kalam. This seminar aimed to inspire students to approach examinations with confidence and resilience, emphasizing the importance of perseverance and self-belief in achieving academic success. Through such initiatives, both teachers and students are empowered to strive for excellence, fostering a culture of continuous learning and growth within our educational community.',
      "image": "./images/damu1.jpg",
      "heading": "06 December 2023"
    },
    {
      "title": "J.R.C & Scout",
      "content": "At our institution, we firmly embrace Mahatma Gandhi's philosophy that serving others is the true path to self-discovery. In line with this belief, we have initiated the formation of FOF (Friends of the Future), Scout, and Red Cross programs within our school community. These initiatives aim to instill values of integrity, brotherhood, and self-discipline among our students while nurturing them to become enlightened citizens of our nation. Through participation in these programs, students not only learn the importance of empathy and compassion but also develop essential life skills such as leadership, teamwork, and problem-solving. The FOF program fosters a sense of social responsibility, encouraging students to actively engage in community service activities and contribute positively to society. Similarly, involvement in Scout and Red Cross activities provides students with opportunities to learn first aid, disaster management, and other valuable skills that enable them to assist those in need. By participating in these programs, students not only enrich their own lives but also make meaningful contributions to the welfare of others, embodying the spirit of service that Mahatma Gandhi advocated. Through FOF, Scout, and Red Cross, our school endeavors to nurture compassionate and socially responsible individuals who are empowered to make a positive difference in the world.",
      "image": "./images/plastic3.jpg",
    },
      {
        "title": "Best Student of The Month",
        "content": "The Best Student of the Month award holds significant importance within our school community as it highlights and celebrates the remarkable achievements of students across all classes. Each month, one outstanding student from every class is selected for this prestigious accolade, symbolizing their dedication, perseverance, and exemplary behavior. This award serves as both recognition and encouragement, motivating students to continue striving for excellence in their academic pursuits and personal development. Recipients of this award are those who consistently demonstrate exceptional academic performance, exhibit exemplary behavior, and display unwavering dedication to their studies. Their achievements not only inspire their peers but also contribute to fostering a positive and supportive learning environment within the classroom. Through the Best Student of the Month award, we aim to cultivate a culture of academic excellence and positive reinforcement, where students are encouraged to reach their full potential and excel in all aspects of their education. Congratulations to all the deserving recipients of this esteemed award, whose hard work, commitment, and exemplary behavior serve as an inspiration to us all.",
        "image": "./images/best2.JPG",
        "heading": "10th February 2023"
      },
      {
        "title": "Scholorship for Rank Holders",
        "content": "Scholarships for rank holders of each class are a commendable initiative undertaken by school management to recognize and reward academic excellence among students. These scholarships serve as a strong motivator for students to excel in their studies, as they understand that their hard work and dedication will be acknowledged and rewarded.By offering scholarships to top performers, schools create a competitive environment that encourages students to strive for the highest levels of academic achievement. This healthy competition fosters a culture of excellence where students are constantly pushing themselves to perform at their best.",
      "content2":"Scholarships for rank holders also promote a well-rounded educational experience by encouraging students to engage in extracurricular activities and community service. Students understand that academic success is not just about grades but also about personal development and contributing positively to society.Moreover, scholarships for rank holders create a sense of fairness and equity within the school community. Students know that their hard work and achievements will be recognized and rewarded regardless of their background or circumstances.Furthermore, scholarships for rank holders inspire students to set ambitious goals and work diligently to achieve them. Knowing that their efforts will be acknowledged and rewarded motivates students to challenge themselves academically.Additionally, scholarships for rank holders encourage students to take ownership of their education and strive for excellence independently. They understand that their academic success is ultimately determined by their own efforts and dedication.Moreover, scholarships for rank holders foster a sense of camaraderie and mutual support among students. Instead of fostering unhealthy competition, they promote collaboration and encouragement among peers to strive for academic success together.Furthermore, scholarships for rank holders create a positive cycle of academic achievement within the school community. As more students strive for excellence and receive recognition for their efforts, it inspires others to do the same, creating a culture of continuous improvement.In conclusion, scholarships for rank holders are a valuable tool for promoting academic excellence, providing financial assistance, nurturing talent, and fostering a supportive and competitive learning environment within schools. They recognize and reward the hard work and dedication of students, inspire them to reach their full potential, and contribute to the overall success and reputation of the school.",
        "image": "./images/month2.JPG",
        "heading": "10th February 2023"
      },
      {
        "title": "English Department Day",
        "content": "English Department Day in SFS  school is a special event that celebrates the achievements of the English department. It focuses on promoting English language skills and showcasing student talents in areas like  drama, writing poem, word plays ,and public speaking. The day typically includes competitions, performances, and exhibitions related to English language and the students of each group performed Skit , Dance and Skit and they were also given marks by the chief guests Fr.Antony Raj and Fr.Wilson and the winners for each competition were awarded. The esteemed chief guest eloquently expounded on the pivotal role of the English language, emphasizing its profound impact in our increasingly interconnected world. They underscored how mastering English can unlock a plethora of opportunities, from facilitating effective communication to enhancing educational and career prospects. The event ended with vote of thanks.",
        "image": "./images/englishdepart.png",
        "heading": "21st October 2023"
      },
      {
        "title": "AI Class",
        "content": "Innovation serves as the catalyst for transformative change, unlocking novel value and driving continual improvement and success. At SFS, a steadfast commitment to innovation permeates every aspect of our institution, as we continually integrate the latest practices across all fields. In response to the imperative of enhancing the education system for our students, SFS School undergoes a multitude of changes, spanning from teaching methodologies to curriculum design. Embracing the burgeoning realm of Artificial Intelligence (AI), our school proudly incorporates this cutting-edge technology into its educational framework. AI represents a burgeoning force that is revolutionizing various industries globally, and SFS School is at the forefront of this transformation by integrating AI into its educational curriculum.",
        "content2":"Artificial Intelligence in Education offers a spectrum of innovative solutions tailored to diverse teaching and learning contexts. By leveraging computer intelligence, AI empowers educators and students alike, enhancing the effectiveness and efficiency of the education system. Through AI-driven tools and platforms, teachers gain access to valuable insights and resources, enabling personalized learning experiences and optimizing instructional strategies. Simultaneously, students benefit from AI-powered educational resources that adapt to individual learning styles, fostering deeper engagement and comprehension. This strategic integration of AI into our educational curriculum underscores SFS School's unwavering commitment to staying at the vanguard of educational innovation, ensuring that our students are equipped with the skills and knowledge to thrive in an ever-evolving world.",
        "image": "./images/AI2.bmp",
      },
      {
        "title": "Christmas Celebration",
        "content": "The school was engulfed in festive cheer as the spirit of Christmas filled the air, with colorful stars and trees adorning every corner. Christmas, a celebration of joy and love, brought the entire school community together in a spirit of warmth and goodwill. Honorable Minister Thiru. V. Meyyanathan (MLA) graced the occasion as the chief guest, imparting a message of caring and sharing to all present. His words resonated with the true essence of Christmas, reminding everyone of the importance of compassion and generosity towards others. As the school radiated with the festive spirit, the message of love and togetherness echoed throughout, fostering a sense of unity and harmony among students, staff, and guests alike.",
        "image": "./images/chrit3.jpg",
        "heading": "14th November 2022"
      },
      {
        "title": "Kamarajar Day",
        "content": "On the 1st of July 2023, Tamil Department observed the joyous celebration of Kamarajar Day, marking the occasion with cultural enthusiasm and pride. Various competitions were organized, each highlighting the profound importance of the Tamil language. Students actively participated, showcasing their linguistic talents and cultural awareness in a series of engaging events.",
        "content2":"The day reached its pinnacle with the vibrant Yellow Day festivities, where participants were not only recognized for their outstanding contributions but also rewarded with prizes. Adding to the grandeur of the occasion, the esteemed Chef Guest, Miss RAGAVI, lent her presence and expertise, elevating the celebration and leaving an indelible mark on the collective spirit of the community. This fusion of cultural programs, linguistic significance, and recognition underscored the commitment to preserving and celebrating the rich heritage of Tamil language and culture.",
        "image": "./images/kam1.jpg",
        "heading": "15th July 2024"
      },
      {
        "title": "Sports & Games",
        "content": "Our school provides various sports and games options such as cricket, football, basketball, table tennis, badminton, and athletics. We organize inter-house and inter-school competitions to promote teamwork and healthy competition. Our sports teachers and coaches offer guidance and training, helping students develop physically, mentally, socially, and emotionally.Participation in games is crucial for a student's development, offering a range of benefits beyond physical fitness. It promotes mental well-being by reducing stress and enhancing cognitive function. Additionally, it fosters important life skills such as teamwork, leadership, discipline, and resilience. Games also improve social interaction and students' holistic growth.",
        "image": "./images/sprts2.JPG",
        "heading": "23rd January 2024"
      },
      {
        "title": "Kindergarten Inagural Day",
        "content": "The Kinder Garden Inaugural Day held on the 5th of July 2023 marked a joyous occasion as it welcomed the newest members, the fertile seeds, to the flourishing garden of learning at SFS. The program, meticulously conducted by the UKG kids, radiated with warmth and enthusiasm as they cheerfully greeted the little children into the school community. Through a delightful blend of storytelling, dance performances, and catchy rhymes, the UKG kids captivated the audience and instilled a sense of excitement and anticipation among the newcomers. As a token of welcome, each child was presented with a sapling, symbolizing growth, and a reminder of their role in nurturing and caring for the environment. Additionally, they were encouraged to plant the sapling in their homes, fostering a connection to nature and instilling values of environmental stewardship from a young age. The Kinder Garden Inaugural Day served as a memorable introduction to the vibrant and nurturing environment of SFS, setting the stage for a fulfilling journey of learning and growth for the little ones. Through this heartwarming event, the school community reaffirmed its commitment to providing a holistic and enriching educational experience for all its students, starting from the very first steps of their educational journey.",
        "image": "./images/kinder11.jpg",
        "heading": "5th July 2023"
      },
      {
        "title": "Animator",
        "content": "The students of SFS are divided into four groups and they are animated by the four animators.The animators of the four groups play a prominent role in shaping students across all fields of learning. They motivate and guide students, encourage active participation, and provide direction for excellence. These animators also facilitate skill development through training and organize events of the school  and offer mentorship to help students overcome challenges. They promote teamwork, instill valuable values, encourage community engagement, and facilitate cultural programs, enriching students' overall educational experience.  The students of each group participate in parades, demonstrating unity and solidarity. The best group of the academic year is awarded.",
        "image": "./images/animators1.jpg",
        "heading": "23rd January 2024"
      },
      {
        "title": "Book Free Saturday",
        "content": "A day dedicated to the joy of reading, a book free day, offers a sanctuary for bibliophiles to immerse themselves in the boundless worlds crafted by words. On this cherished day, individuals set aside the hustle and bustle of daily life, carving out precious moments to lose themselves in the pages of a captivating book. It becomes a respite from the digital noise and a deliberate pause to reconnect with the tangible delight of flipping through pages, savoring the scent of paper, and getting lost in the narratives that unfold.",

      "content2":"A book free day not only nurtures a love for literature but also promotes mental well-being by providing an escape into different realms of imagination. It offers solace, inspiration, and an opportunity to delve into the depths of knowledge. This intentional break from screens and constant connectivity allows for introspection, relaxation, and a rejuvenation of the mind, fostering a community that appreciates the transformative power of literature in a world that often races against time.",
        "image": "./images/bkn.JPG",
      },
      {
        "title": "VII Class Day",
        "content": "With realisation of one's own potential and self confidence in one's ability , one can build a better tomorrow and find a tenet of his own adeptness. The SFS  stands not only for its scholastic superiority but also  to offer ample opportunities to substantiate the pupils' innate latent knacks. We celebrate class day for each class . Our students shine in one or other spheres of excellence. It's absolutely their day where they rock the stage and tell their parents of their proficiency. This is mainly organised so as to make every student of a class to touch the stage which build their confidence.",
        "image": "./images/7cld5.JPG",
        "heading": "28th October 2023"
      },
      {
        "title": "VI Class Day",
        "content": "With realisation of one's own potential and self confidence in one's ability , one can build a better tomorrow and find a tenet of his own adeptness. The SFS  stands not only for its scholastic superiority but also  to offer ample opportunities to substantiate the pupils' innate latent knacks. We celebrate class day for each class . Our students shine in one or other spheres of excellence. It's absolutely their day where they rock the stage and tell their parents of their proficiency. This is mainly organised so as to make every student of a class to touch the stage which build their confidence.",
        "image": "./images/clss1.JPG",
        "heading": "24th July 2023"
      },
      {
        "title": "Tamil Department Day",
        "content": "Department department day in SFS school is a departmental celebration in which each individual group celebrates its achievements by organising various  cultural and competitive activities among the four houses.Students who win the competitions are awarded by the respective Department during the department day.Sfs organises five department days. Tamil department day was celebrated on 15 of July and various competitions were conducted. In the afternoon colored with the culture programmes the winners were awarded. It was celebrated as the Educational Development Day. Miss.G.RAGAVI the deputy superintendent of police, Pudukkottai presided over the event and 'The chief guest delivered an engaging and insightful speech, highlighting the importance of perseverance and education in achieving success. Her words were inspiring everyone to strive for excellence in their endeavors emphasizing the value of education and encouraged students to pursue their dreams with passion. Skit on life of Kamarajar was performed by the students. The event ended with vote of thanks .",

      "content2":"Moreover, Tamil Department Day is not merely a commemoration but also a reflection of the ongoing efforts to preserve and promote the Tamil language. It highlights the importance of language as a cultural identity and encourages individuals to take pride in their linguistic heritage. The festivities not only contribute to the academic and cultural development of Tamil studies but also serve as a source of inspiration for future generations to connect with and appreciate the profound contributions of the Tamil language to literature, philosophy, and the arts.",
        "image": "./images/td7.JPG",
        "heading": "15th July 2023"
      },
      {
        "title": "Award For Spoken English",
        "content": ". A student from each section and a class  from each standard are given award by the spoken English trainers for their constant effort in n keeping up the rule of language and for being an example for the other students.The Spoken English Award is presented to students who exhibit a strong command of the language, emphasizing adherence to its rules.",
        "image": "./images/sp4.jpeg",
        "heading": "23rd January 2024"
      },
      {
        "title": "Study Tour For 1st Std",
        "content": "A school study tour encompasses an extensive visit to diverse local educational and cultural sites, profoundly impacting students' learning. These tours offer immersive, hands-on experiences that bring classroom lessons to life, fostering a deeper understanding of subjects and broadening students' perspectives. Every class gets this chance and the students are positively impressed by the different ways of learning.",

      "content2":"The aim of organizing study tours for every class is to provide students with experiential learning opportunities outside the traditional classroom setting. These tours are designed to complement and enrich classroom learning by offering hands-on experiences that stimulate curiosity, encourage exploration, and promote a deeper understanding of various subjects. By exposing students to different cultures, environments, and educational contexts, these trips aim to broaden their horizons, foster personal growth, and cultivate a lifelong love for learning.Every class gets this chance and the students are positively impressed by the different ways of learning.",
        "image": "./images/visit2.jpg",
        "heading": "23rd January 2024"
      },
  ]
